### ISSUE TITLE
`check`: Error message is unclear when hot repo is referencing unindexed packs of different type

### ISSUE THREAD

**Issue by Kreeblah** [rustic-rs/rustic#1229]
I'm using rustic 0.8.0 on both FreeBSD 14 and macOS 14, and in both cases, I'm seeing a number of things like this show up:

```
[WARN] pack d4f30393 not referenced in index. Can be a parallel backup job. To repair: 'rustic repair index'.
```

The thing is, running a prune or a repair index doesn't seem to fix those warnings.  However, running `restic check` on the same repo doesn't report the unindexed packs that `rustic check` does.  Instead, it reports a clean repository.

Is there something I'm doing wrong here?  This is using Wasabi S3 for a backend.

**Comment by KamikazeePL** [comment]
Run `restic repair index` it should fix it

**Comment by simonsan** [comment]
Any updates on this? Did you fix it or is the issue still persisting?

**Comment by Kreeblah** [comment]
No, I haven't been able to figure out what's going on.  Even after running `restic repair index`, I'm still seeing the same warnings with `rustic check`, whereas `restic check` reports no issues.

**Comment by aawsome** [comment]
@Kreeblah can you please post the output of `rustic repoinfo`? I'd like to find a good strategy how to manually debug what's going on..

**Comment by Kreeblah** [comment]
Sure.  Here you go:

```
[INFO] using config /Users/myuser/Library/Application Support/rustic/rustic.toml
[00:00:03] scanning files...                                                    [INFO] repository opendal:bucketname#opendal:bucketname: password is correct.
[INFO] using cache at /Users/myuser/Library/Caches/rustic/2b531df565410f7772e1fd9450cab4b09aef746218035d588be9f531c9d2622e
[00:00:00] scanning index...              ████████████████████████████████████████         29/29        repository files

| File type | Count | Total Size |
|-----------|-------|------------|
| Key       |     1 |      363 B |
| Snapshot  |     2 |    1.1 kiB |
| Index     |    29 |   65.2 MiB |
| Pack      |  9079 |  403.9 GiB |
| Total     |  9111 |  404.0 GiB |

hot repository files

| File type | Count | Total Size |
|-----------|-------|------------|
| Key       |     1 |      363 B |
| Snapshot  |     2 |    1.1 kiB |
| Index     |    29 |   65.2 MiB |
| Pack      |  9079 |  403.9 GiB |
| Total     |  9111 |  404.0 GiB |


| Blob type |   Count | Total Size | Total Size in Packs |
|-----------|---------|------------|---------------------|
| Tree      |  134841 |    2.3 GiB |             1.0 GiB |
| Data      | 1267394 |  489.4 GiB |           402.9 GiB |
| Total     | 1402235 |  491.7 GiB |           403.9 GiB |

| Blob type  | Pack Count | Minimum Size | Maximum Size |
|------------|------------|--------------|--------------|
| Tree packs |         43 |      5.4 kiB |    468.0 MiB |
| Data packs |       9036 |      3.3 MiB |     58.6 MiB |
```

**Comment by aawsome** [comment]
@Kreeblah sorry for coming back so late..
Actually I would like to wait for #1254 which allows to better debug the index of your repository.

**Comment by Kreeblah** [comment]
Sure, that works.  I'll keep an eye out for the next release, then, so I can run those commands.

**Comment by simonsan** [comment]
> Sure, that works. I'll keep an eye out for the next release, then, so I can run those commands.

We'll need to fix the `nightly` CD pipeline, and then we can offer you a nightly release to test, we'll let you know.

**Comment by aawsome** [comment]
@Kreeblah You can use rustic 0.9.0 to further investigate this.

Can you please pick one of the packs which are claimed to be unindexed, and run 

`rustic list packs | grep <PACKID>`

and 

`rustic list indexpacks | grep <PACKID>`?

Thanks a lot!

**Comment by aawsome** [comment]
@Kreeblah Could it be that this is a hot/cold repository and you have that data pack file in the hot part of your repository?

**Comment by Kreeblah** [comment]
Unfortunately, no.  I'm not using the hot/cold feature.  Here's a (sanitized) copy of the config for this particular backup:

```
[repository]
repo-hot = "opendal:s3"
repository = "opendal:s3"
password="MYPASSWORD"

[repository.options]
bucket = "MYBUCKET"
root = "/"
endpoint = "https://s3.us-west-1.wasabisys.com"
region = "us-west-1"
access_key_id="MYACCESSKEY"
secret_access_key="MYSECRETACCESSKEY"

[backup]
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]

[[backup.snapshots]]
sources = ["/Users/myuser"]
git-ignore = true
```

**Comment by aawsome** [comment]
> repo-hot = "opendal:s3"

if you remove this line, you have a "normal" repository. With this line it is treated as a hot/cold repository...

**Comment by Kreeblah** [comment]
*sigh*  Originally, I was going to set it up as a hot/cold repo, but decided not to.  And, apparently I forgot to remove that line.  That would explain what's going on, I suppose.

**Comment by aawsome** [comment]
Actually I think we should make the error message a bit more clear here and output something like `hot pack ffebbfc0 not referenced as tree pack in index, but as data pack.` 

I'll try to update `check`...
